version: '3'
services:
  backend:
    build: './backend'
    ports:
      - "3000:3000"
    volumes:
      - './backend:/app'
      - './backend/prisma:/app/prisma'
    env_file:
      - './backend/.env'
    command: npm run dev
    depends_on:
      - database

  frontend:
    build: './frontend'
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev 
    depends_on:
      - backend

  database:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
